services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blog-strapi
    ports:
      - "5432:5432"
    volumes:
      - ~/PostgreeDB:/var/lib/postgresql/data

